# Generated by Django 3.0.5 on 2020-04-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('infected_count', models.IntegerField(default=0)),
                ('recovered_count', models.IntegerField(default=0)),
                ('died_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('is_infected', models.BooleanField(blank=True, default=False)),
                ('infected_date', models.DateField(blank=True, null=True)),
                ('is_recovered', models.BooleanField(blank=True, default=False)),
                ('is_died', models.BooleanField(blank=True, default=False)),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('infected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
