# Generated by Django 3.0.5 on 2020-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_died',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_infected',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_recovered',
            field=models.NullBooleanField(default=False),
        ),
    ]
