# Generated by Django 3.0.4 on 2020-04-26 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='died_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='infected_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='recovered_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='died_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='infected_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='recovered_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='infected_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.AlterField(
            model_name='region',
            name='died_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='infected_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='recovered_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
